# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=2)),
                ('img_url', models.CharField(max_length=2000)),
            ],
        ),
    ]
