# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
